name: PR Agent

on:
  pull_request:
    types: [opened, reopened, ready_for_review]
  issue_comment:
    types: [created, edited]

jobs:
  pr_agent_job:
    if: ${{ github.event.sender.type != 'Bot' }}
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
      contents: write

    steps:
      - name: Run PR-Agent
        uses: qodo-ai/pr-agent@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

          # --- Model Configuration ---
          config.model: "openai/Qwen/Qwen3-235B-A22B-Instruct-2507" # Or use real model name below
          config.fallback_models: "openai/Qwen/Qwen3-235B-A22B-Instruct-2507"
          config.custom_model_max_tokens: "128000"

          # --- OpenAI-Compatible vLLM Endpoint ---
          OPENAI.API_BASE: "https://codex.datax.iliad.fr/v1"
          OPENAI.KEY: ${{ secrets.OPENAI_KEY }}

          # --- Automation Settings (Optional) ---
          github_action_config.auto_review: "true"
          github_action_config.auto_describe: "true"
          github_action_config.auto_improve: "true"
